telnet dev.virtualearth.net 80

POST /webservices/v1/geocodeservice/geocodeservice.svc HTTP/1.1
User-Agent: curl/7.39.0
Host: dev.virtualearth.net
Accept: */*
Content-Type: text/xml; charset=utf-8
SOAPAction: "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/ReverseGeocode"
Content-Length: 878

<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><ReverseGeocode xmlns="http://dev.virtualearth.net/webservices/v1/geocode/contracts"><request><ns1:Credentials xmlns:ns1="http://dev.virtualearth.net/webservices/v1/common"><ns1:ApplicationId>Aq1QPoKBKDlQiaWwyelP6cborOQhPIESPZWnP1HNk_bZ5c6BuGLamptciyuGD_-n</ns1:ApplicationId></ns1:Credentials><ns2:Location xmlns:ns2="http://dev.virtualearth.net/webservices/v1/geocode"><ns3:Latitude xmlns:ns3="http://dev.virtualearth.net/webservices/v1/common">-37.802867</ns3:Latitude><ns4:Longitude xmlns:ns4="http://dev.virtualearth.net/webservices/v1/common">144.950338</ns4:Longitude></ns2:Location></request></ReverseGeocode></soapenv:Body></soapenv:Envelope>

#Expected response:
#<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><ReverseGeocodeResponse xmlns="http://dev.virtualearth.net/webservices/v1/geocode/contracts"><ReverseGeocodeResult xmlns:a="http://dev.virtualearth.net/webservices/v1/geocode" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><BrandLogoUri xmlns="http://dev.virtualearth.net/webservices/v1/common">http://dev.virtualearth.net/Branding/logo_powered_by.png</BrandLogoUri><ResponseSummary xmlns="http://dev.virtualearth.net/webservices/v1/common"><AuthenticationResultCode>ValidCredentials</AuthenticationResultCode><Copyright>Copyright © 2017 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation.</Copyright><FaultReason i:nil="true"/><StatusCode>Success</StatusCode><TraceId>59bed99b3bcd409c8954bc952b0618c2|BN20240253|7.7.0.0|BN1SCH010134740</TraceId></ResponseSummary><a:Results xmlns:b="http://dev.virtualearth.net/webservices/v1/common"><b:GeocodeResult><b:Address><b:AddressLine>2 Lancashire Ln</b:AddressLine><b:AdminDistrict>VIC</b:AdminDistrict><b:CountryRegion>Australia</b:CountryRegion><b:District/><b:FormattedAddress>2 Lancashire Ln, North Melbourne, VIC 3051</b:FormattedAddress><b:Locality>North Melbourne</b:Locality><b:PostalCode>3051</b:PostalCode><b:PostalTown/></b:Address><b:BestView><b:Northeast><b:Altitude>0</b:Altitude><b:Latitude>-37.799004282429323</b:Latitude><b:Longitude>144.95685598773105</b:Longitude></b:Northeast><b:Southwest><b:Altitude>0</b:Altitude><b:Latitude>-37.806729717570676</b:Latitude><b:Longitude>144.94382001226893</b:Longitude></b:Southwest></b:BestView><b:Confidence>Medium</b:Confidence><b:DisplayName>2 Lancashire Ln, North Melbourne, VIC 3051</b:DisplayName><b:EntityType>Address</b:EntityType><b:Locations><b:GeocodeLocation><b:Altitude>0</b:Altitude><b:Latitude>-37.802867</b:Latitude><b:Longitude>144.950338</b:Longitude><b:CalculationMethod>Interpolation</b:CalculationMethod></b:GeocodeLocation></b:Locations><b:MatchCodes xmlns:c="http://schemas.microsoft.com/2003/10/Serialization/Arrays"><c:string>Good</c:string></b:MatchCodes></b:GeocodeResult></a:Results></ReverseGeocodeResult></ReverseGeocodeResponse></s:Body></s:Envelope>